# Generated by Django 2.0.1 on 2020-06-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200620_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='auther',
            new_name='author',
        ),
    ]
